disabled_rules:
  - line_length
  - file_length
  - non_optional_string_data_conversion
  - type_body_length
  - type_name  
  - identifier_name
  - opening_brace
  - function_body_length 

included:
  - Sources
  - Tests

opt_in_rules:
  - array_init
  - collection_alignment
  - comma_inheritance
  - convenience_type
  - closure_spacing
  - direct_return
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - identical_operands
  - indentation_width
  - joined_default_parameter
  - modifier_order
  - overridden_super_call
  - toggle_bool
  - switch_case_alignment:
    indented_cases: false
  - fallthrough

nesting:
  type_level:
    warning: 2

large_tuple:
  warning: 3
  error: 4

reporter: "xcode"
