disabled_rules:
  - identifier_name
  - todo
  - type_name
  - trailing_comma # Conflicts with SwiftFormat
  - function_body_length
  - opening_brace
  - type_body_length

opt_in_rules:
  - array_init
  - collection_alignment
  - comma_inheritance
  - convenience_type
  - closure_spacing
  - direct_return
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - identical_operands
  - indentation_width
  - joined_default_parameter
  - modifier_order
  - overridden_super_call
  - toggle_bool
  - switch_case_alignment:
    indented_cases: false
  - fallthrough

nesting:
  type_level:
    warning: 2

reporter: "xcode"
