name: checkout-sheet-kit-swift

type: ios

packages:
  - xcode
  - homebrew:
      - swiftlint
      - swiftformat
      - xcbeautify
      - rover
      - jq

up:
  - ruby
  - custom:
      name: Ensure Storefront.xcconfig file
      met?: |
        ([ -f "./samples/MobileBuyIntegration/Storefront.xcconfig" ] || exit 1)
      meet: ./scripts/ensure_storefront_config
  - custom:
      name: Setup entitlements
      met?: |
        ([ -f "./samples/MobileBuyIntegration/MobileBuyIntegration/MobileBuyIntegration.entitlements" ] || exit 1;)
      meet: ./scripts/setup_entitlements

check:
  lint: /opt/dev/bin/dev lint

commands:
  lint:
    aliases: [style]
    desc: Check format and lint issues across all Swift files using SwiftLint and SwiftFormat
    run: scripts/lint
  fix:
    desc: Automatically fix format and lint issues where possible
    run: scripts/lint fix
  build:
    subcommands:
      packages:
        desc: Build both ShopifyCheckoutSheetKit and ShopifyAcceleratedCheckouts packages
        run: |
          ./scripts/xcode_run build ShopifyCheckoutSheetKit
          ./scripts/xcode_run build ShopifyAcceleratedCheckouts
      samples:
        desc: Build all sample applications to verify integration
        run: ./scripts/build_samples
  test:
    subcommands:
      packages:
        desc: Run all unit and integration tests for the packages
        run: |
          ./scripts/xcode_run test ShopifyCheckoutSheetKit-Package
      samples:
        desc: Run tests for sample applications
        run: ./scripts/test_samples

  apollo:
    subcommands:
      download_schema:
        desc: Download GraphQL Schema
        run: |
          cd Samples/ShopifyAcceleratedCheckoutsApp
          BUILD_SETTINGS=$(xcodebuild -showBuildSettings -scheme ShopifyAcceleratedCheckoutsApp -json | jq -r '.[0].buildSettings')
          TOKEN=$(echo "$BUILD_SETTINGS" | jq -r '.STOREFRONT_ACCESS_TOKEN')
          DOMAIN=$(echo "$BUILD_SETTINGS" | jq -r '.STOREFRONT_DOMAIN')
          API_VERSION=$(echo "$BUILD_SETTINGS" | jq -r '.API_VERSION')
          rover graph introspect https://$DOMAIN/api/$API_VERSION/graphql --header="X-Shopify-Storefront-Access-Token: $TOKEN" --output schema.$API_VERSION.graphqls

      codegen:
        desc: Generate Apollo Client models and request functions for sample app
        run: |
          cd ./Samples/ShopifyAcceleratedCheckoutsApp/
          ./apollo-ios-cli generate 
          /opt/dev/bin/dev fix
