name: checkout-sheet-kit-swift

type: ios

up:
  - ruby
  - custom:
      name: Ensure Storefront.xcconfig file
      met?: |
        ([ -f "./samples/MobileBuyIntegration/Storefront.xcconfig" ] || exit 1)
      meet: ./scripts/ensure_storefront_config
  - custom:
      name: Setup entitlements
      met?: |
        ([ -f "./samples/MobileBuyIntegration/MobileBuyIntegration/MobileBuyIntegration.entitlements" ] || exit 1;)
      meet: ./scripts/setup_entitlements
  - custom:
      name: Setup Git Hooks
      met?: |
        PRE_COMMIT_DEST=".git/hooks/pre-commit"
        
        # Check if it's a symlink pointing to the correct location
        if [ -L "$PRE_COMMIT_DEST" ] && [ "$(readlink "$PRE_COMMIT_DEST")" = "../../Scripts/pre-commit" ]; then
          exit 0
        else
          exit 1
        fi
      meet: |
        ln -sf ../../Scripts/pre-commit .git/hooks/pre-commit

packages:
  - xcode
  - homebrew:
      - swiftlint
      - swiftformat

commands:
  lint:
    desc: Check Format & Lint issues
    run: scripts/lint
  fix:
    desc: Autofix Format & Lint issues
    run: scripts/lint fix