name: 🐛 Bug Report
description: Something is wrong with the Checkout Sheet Kit.
labels:
  - 'Bug'
body:
  - type: markdown
    attributes:
      value: |
        ## Hi there!

        If your issue is **not** related to the Checkout Sheet Kit itself, but rather an internal checkout or storefront problem, please reach out to Shopify support directly where the issue will be triaged correctly.

  - type: dropdown
    attributes:
      label: What area is the issue related to?
      options:
        - Checkout Sheet Kit
        - Storefront API
        - Multipass
        - Lifecycle methods
        - Web Pixels
        - Other / I don't know
    validations:
      required: true

  - type: input
    attributes:
      label: What version of Checkout Sheet Kit are you using?
      description: Please list the package version and device you are testing with.
    validations:
      required: true

  - type: input
    attributes:
      label: Reproducible sample code
      description: Please provide examples of code relating to your issue. This might include GraphQL queries to the Storefront API to create a cart, or native code to present the checkout URL. Providing this will help us debug your issue more quickly.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: A list of steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots/Videos/Log output
    validations:
      required: false

  - type: textarea
    attributes:
      label: Storefront domain
      placeholder: your-storefront-name.myshopify.com
      description: This will expedite our search for any errors that occurred.
    validations:
      required: true
