name: 💡 Feature Request
description: An idea or suggestion for a new feature or enhancement to the Checkout Sheet Kit
labels: ["Feature-Request", "untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        ## Hi there!

        Please tell us about the new feature or enhancement you'd like to see implemented in the Checkout Sheet Kit.

  - type: textarea
    attributes:
      label: Description
      description: A detailed description of the feature or enhancement you'd like to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Rationale
      description: Explain the benefits of this feature.
    validations:
      required: true
