#!/usr/bin/env bash

set -ex
set -eo pipefail

if [[ -n $CURRENT_SIMULATOR_UUID ]]; then
    dest="id=$CURRENT_SIMULATOR_UUID"
else
    dest="platform=iOS Simulator,name=iPhone 16"
fi

xcodebuild clean test -scheme ShopifyCheckoutSheetKit-Package -sdk iphonesimulator -destination "$dest" -skipPackagePluginValidation
