name: Deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  cocoapods:
    runs-on: ${{ vars.MACOS_RUNNER }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
        with:
          bundler-cache: true

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          bundle exec pod lib lint --allow-warnings --verbose
          bundle exec pod trunk push --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
