name: Deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  cocoapods:
    runs-on: ${{ vars.MACOS_RUNNER }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: ruby/setup-ruby@dffb23f65a78bba8db45d387d5ea1bbd6be3ef18 # v1.293.0
        with:
          bundler-cache: true

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          bundle exec pod lib lint --allow-warnings --verbose
          bundle exec pod trunk push --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
