name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  # swiftlint is a separate/duplicate effort here, as it will also report to Annotations
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684 # 3.2.1
        with:
          args: --strict

  swiftformat:
    name: SwiftFormat & SwiftLint
    runs-on: ${{ vars.MACOS_RUNNER }}
    env:
      MINT_PATH: ${{ github.workspace }}/.mint/lib
      MINT_LINK_PATH: ${{ github.workspace }}/.mint/bin
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache Mint packages
        id: mint-cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Bootstrap Mint packages
        if: steps.mint-cache.outputs.cache-hit != 'true'
        run: mint bootstrap --link

      - name: Add Mint to PATH
        run: echo "${{ github.workspace }}/.mint/bin" >> "$GITHUB_PATH"

      - run: ./Scripts/lint check --verbose --skip-pod

  check-license-headers:
    name: License Headers
    runs-on: ${{ vars.MACOS_RUNNER }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: ./Scripts/ensure_license

  lint-podspec:
    name: CocoaPods
    runs-on: ${{ vars.MACOS_RUNNER }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          bundler-cache: true
      - run: bundle exec pod lib lint --allow-warnings
